version: "3.7"

services:
  prometheus-java-metrics-example:
    container_name: "prometheus-java-metrics-example"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: "unless-stopped"
